grails-app/domain/Comentario.groovy
package empeduc

class Comentario {

    static constraints = {
    }
    
    String texto
    Date dia
    Topico topico
}

grails-app/domain/Topico.groovy
package empeduc

class Topico {

    static constraints = {
    }
    
    static hasMany = [comentarios:Comentario]
    Forum forum
    String topico
    
    
}

grails-app/controllers/empeduc/TopicoController.groovy
package empeduc

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class TopicoController {

    TopicoService topicoService
    ComentarioService comentarioService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond topicoService.list(params), model:[topicoCount: topicoService.count()]
    }

    def show(Long id) {
        respond topicoService.get(id)
        respond comentarioService.list(params), model:[comentarioCount: comentarioService.count()]
        
    }

    def create() {
        respond new Topico(params)
    }

    def save(Topico topico) {
        if (topico == null) {
            notFound()
            return
        }

        try {
            topicoService.save(topico)
        } catch (ValidationException e) {
            respond topico.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'topico.label', default: 'Topico'), topico.id])
                redirect topico
            }
            '*' { respond topico, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond topicoService.get(id)
    }
    
    def comentar(Long id){
        redirect (uri : '/comentario/create', params: [topico: id])        
    }

    def update(Topico topico) {
        if (topico == null) {
            notFound()
            return
        }

        try {
            topicoService.save(topico)
        } catch (ValidationException e) {
            respond topico.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'topico.label', default: 'Topico'), topico.id])
                redirect topico
            }
            '*'{ respond topico, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        topicoService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'topico.label', default: 'Topico'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'topico.label', default: 'Topico'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/topico/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'topico.label', default: 'Topico')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-topico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-topico" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.topico}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.topico}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.topico}" method="POST">
                <fieldset class="form">
                    <f:all bean="topico"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/topico/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'topico.label', default: 'Topico')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-topico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-topico" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.topico}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.topico}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.topico}" method="PUT">
                <g:hiddenField name="version" value="${this.topico?.version}" />
                <fieldset class="form">
                    <f:all bean="topico"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/topico/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'topico.label', default: 'Topico')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-topico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-topico" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${topicoList}" />

            <div class="pagination">
                <g:paginate total="${topicoCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/topico/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" contet="width=device-width, inicial-scale=1.0">
        
        
        <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
        <meta charset="utf-8" />
        <title>EMPEDUC</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <!-- BEGIN CORE CSS FRAMEWORK -->
        <link href="${resource(dir: 'template', file:'/plugins/pace/pace-theme-flash.css')}" rel="stylesheet" type="text/css" media="screen"/>
        <link href="${resource(dir: 'template', file:'/plugins/boostrapv3/css/bootstrap.min.css')}" rel="stylesheet" type="text/css"/>
        <link href="${resource(dir: 'template', file:'/plugins/boostrapv3/css/bootstrap-theme.min.css')}" rel="stylesheet" type="text/css"/>
        <link href="${resource(dir: 'template', file:'/plugins/font-awesome/css/font-awesome.css')}" rel="stylesheet" type="text/css"/>
        <link href="${resource(dir: 'template', file:'/css/animate.min.css" rel="stylesheet')}" type="text/css"/>
        <link href="${resource(dir: 'template', file:'/plugins/jquery-scrollbar/jquery.scrollbar.css')}" rel="stylesheet" type="text/css"/>
        <!-- END CORE CSS FRAMEWORK -->
        <!-- BEGIN CSS TEMPLATE -->
        <link href="${resource(dir: 'template', file:'/css/style.css')}" rel="stylesheet" type="text/css"/>
        <link href="${resource(dir: 'template', file:'/css/responsive.css')}" rel="stylesheet" type="text/css"/>
        <link href="${resource(dir: 'template', file:'/css/custom-icon-set.css')}" rel="stylesheet" type="text/css"/>
        
        <g:set var="entityName" value="${message(code: 'topico.label', default: 'Topico')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body class="">
    <!-- BEGIN HEADER -->
        <div class="header navbar navbar-inverse "> 
          <!-- BEGIN TOP NAVIGATION BAR -->
            <div class="navbar-inner">
                <div class="header-seperation"> 
                    <ul class="nav pull-left notifcation-center" id="main-menu-toggle-wrapper" style="display:none">	
                        <li class="dropdown"> <a id="main-menu-toggle" href="#main-menu"  class="" > <div class="iconset top-menu-toggle-white"></div> </a> </li>		 
                    </ul>

                </div>
                <!-- END RESPONSIVE MENU TOGGLER --> 
                <div class="header-quick-nav" > 
                    <div class="pull-right"> 
                        <div class="chat-toggler">	
                            <div class="profile-pic"> 
                                <img src="/assets/img/profiles/avatar_small.jpg"  alt="" data-src="/assets/img/profiles/avatar_small.jpg" data-src-retina="/assets/img/profiles/avatar_small2x.jpg" width="35" height="35" /> 
                            </div>
                            <div class="talkballon">
                                <div class="talk-bubble tri-right right-in">
                                    <div class="talktext">
                                        <p id="talkballon">Teste</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> 
                <!-- END TOP NAVIGATION MENU --> 
            </div>
            <!-- END TOP NAVIGATION BAR --> 
        </div>
        <!-- END HEADER -->


        <!-- BEGIN CONTAINER -->
        <g:render template="../menulateral" />
                          
           <br>
                          
                          
        <!-- BEGIN PAGE CONTAINER-->
          <div class="page-content"> 
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="content"> 
                
               
        <div class="nav" role="navigation">
            <ul style="list-style:none">
                <li style="display:inline"><a class="btn btn-primary btn-cons" href="${createLink(uri: '/')}"><i class="fa fa-home">&nbsp</i><g:message code="default.home.label"/></a></li>
                <li style="display:inline"><g:link class="btn btn-primary btn-cons" action="index"><i class="fa fa-list-alt">&nbsp</i><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <sec:ifAnyGranted roles='ROLE_ADMIN,ROLE_PROFESSOR,ROLE_DIRETOR'>
                    <li style="display:inline"><g:link class="btn btn-primary btn-cons" action="create"><i class="fa fa-plus">&nbsp</i><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                </sec:ifAnyGranted>
            </ul>
        </div>
        <br><br>
        <div>
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="topico" />
            
                <g:form resource="${this.topico}" method="DELETE">
                    <fieldset class="buttons">
                        
                        <sec:ifAnyGranted roles='ROLE_ADMIN,ROLE_PROFESSOR,ROLE_DIRETOR'>
                            <g:link class="btn btn-primary btn-cons" action="edit" resource="${this.topico}"><i class="fa fa-edit">&nbsp</i><g:message code="default.button.edit.label" default="Edit" /></g:link>
                            <button class="btn btn-primary btn-cons" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"><i class="fa fa-trash-o">&nbsp</i>${message(code: 'default.button.delete.label', default: 'Delete')}</button>
                        </sec:ifAnyGranted>
                    </fieldset>
                </g:form>
            
        </div>
        
        <br><br><br>
        
        <div>
        
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>

            <h1>Comentários &nbsp <g:link class="btn btn-primary btn-cons" action="comentar" resource="${this.topico}"><i class="fa fa-comments">&nbsp</i>Comentar</g:link> </h1>

            <f:table domainClass="empeduc.Comentario" collection="${comentarioList}" />
        
        </div>
        
        
        
        
    </div>
            </div>  
           <!-- END CONTAINER --> 
          </div>
          <!-- END CONTAINER -->
        
        
    <!-- BEGIN CORE JS FRAMEWORK--> 
          <script src="${resource(dir: 'template', file:'plugins/jquery-1.8.3.min.js')}" type="text/javascript"></script> 
          <script src="${resource(dir: 'template', file:'plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js')}" type="text/javascript"></script> 
          <script src="${resource(dir: 'template', file:'plugins/boostrapv3/js/bootstrap.min.js"')}"type="text/javascript"></script> 
          <script src="${resource(dir: 'template', file:'plugins/breakpoints.js')}" type="text/javascript"></script> 
          <script src="${resource(dir: 'template', file:'plugins/jquery-unveil/jquery.unveil.min.js')}" type="text/javascript"></script> 
          <script src="${resource(dir: 'template', file:'plugins/jquery-scrollbar/jquery.scrollbar.min.js')}" type="text/javascript"></script>
          <!-- END CORE JS FRAMEWORK --> 
          <!-- BEGIN PAGE LEVEL JS --> 
          <script src="${resource(dir: 'template', file:'plugins/pace/pace.min.js')}" type="text/javascript"></script>  
          <script src="${resource(dir: 'template', file:'plugins/jquery-scrollbar/jquery.scrollbar.min.js')}" type="text/javascript"></script>
          <script src="${resource(dir: 'template', file:'plugins/jquery-block-ui/jqueryblockui.js"')}" type="text/javascript"></script>
          <script src="${resource(dir: 'template', file:'plugins/jquery-sparkline/jquery-sparkline.js')}" type="text/javascript"></script>
          <script src="${resource(dir: 'template', file:'plugins/jquery-numberAnimate/jquery.animateNumbers.js')}" type="text/javascript"></script>
          <!-- END PAGE LEVEL PLUGINS --> 	

          <!-- BEGIN CORE TEMPLATE JS --> 
          <script src="${resource(dir: 'template', file:'js/core.js" type="text/javascript')}"></script> 
          <script src="${resource(dir: 'template', file:'js/chat.js" type="text/javascript')}"></script>
          <script src="${resource(dir: 'template', file:'js/demo.js" type="text/javascript')}"></script>
          <!-- END CORE TEMPLATE JS --> 
        
    </body>
</html>